source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'HDUtil_Example' do
  pod 'HDUtil', :path => '../'

  target 'HDUtil_Tests' do
    inherit! :search_paths
  end
  
end
